buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.frgaal:compiler-gradle-plugin:15.0.0"
        classpath "org.netbeans.html:html4j-maven-plugin:1.7.1"
    }
}

apply plugin: 'java'
apply plugin: 'html4j'
apply plugin: 'org.openjfx.javafxplugin'
apply plugin: 'org.frgaal.compiler'

targetCompatibility = '1.8'
sourceCompatibility = '15'

javafx {
    version = '15';
    modules = [ 'javafx.web' ]
    configuration = 'testRuntime'
}

dependencies {
    compile "org.netbeans.html:net.java.html.json:1.7.1"
    compile "org.netbeans.html:net.java.html.boot:1.7.1"
    compile "com.dukescript.api:javafx.base:8.60.11"
    compile "com.dukescript.api:javafx.beaninfo:0.6"
    compileOnly "org.netbeans.api:org-openide-util-lookup:RELEASE120-u1"
    compileOnly "org.apidesign.bck2brwsr:core:0.54"
    annotationProcessor "org.netbeans.html:net.java.html.boot:1.7.1"
    annotationProcessor "org.netbeans.html:net.java.html.json:1.7.1"
    annotationProcessor "org.netbeans.api:org-openide-util-lookup:RELEASE120-u1"
    testCompile "com.dukescript.api:junit-browser-runner:1.0"
    testRuntime "org.netbeans.html:net.java.html.boot.fx:1.7.1"
    testAnnotationProcessor files("build/classes/java/main/")
}

task copyReactResources(type: Copy) {
    from 'src/main/resources' into 'build/classes/java/main/';
}

compileJava.dependsOn(copyReactResources);
