buildscript {
    ext.bck2brwsr_version = '0.54'

    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.apidesign.bck2brwsr:bck2brwsr-maven-plugin:$bck2brwsr_version"
    }
}

apply plugin: 'java'
apply plugin: 'bck2brwsr'



java {
   disableAutoTargetJvm()
}

targetCompatibility = '1.8'
sourceCompatibility = '1.8'

mainClassName = 'cz.xelfi.demo.react4jdemo.BrowserMain'


def commonProject = project.parent

dependencies {
    compile commonProject
}

configurations.bck2brwsr {
    exclude group: 'org.jetbrains', module: 'annotations'
}

bck2brwsrPages.from {
    fileTree("${commonProject.projectDir}/src/main/webapp/pages") +
    fileTree("${commonProject.projectDir}/src/main/java/cz/xelfi/demo/react4jdemo")
}
bck2brwsrAot.dependsOn(bck2brwsrPages)
