plugins {
    id 'java'
    id 'application'
}

def commonProject = project.parent
def jdk8 = System.getProperty("java.version").startsWith("1.8")

mainClassName = 'cz.xelfi.demo.react4jdemo.DesktopMain'

distributions {
    main {
        baseName = commonProject.name + '-desktop'
        contents {
            from "${commonProject.projectDir}/src/main/webapp/"
        }
    }
}
tasks.run {
    jvmArgs "-Dbrowser.rootdir=${commonProject.projectDir}/src/main/webapp/"
}

apply plugin: 'org.openjfx.javafxplugin'
apply plugin: 'html4j'

javafx {
    version = "11"
    modules = ["javafx.web"]
}

dependencies {
    compile commonProject
    compile "org.netbeans.html:net.java.html.boot:1.7.2"
    runtime "org.netbeans.html:net.java.html.boot.fx:1.7.2"
    runtime "org.netbeans.html:xhr4j:1.7.2"
    testCompile "com.dukescript.api:junit-browser-runner:1.0"
    testRuntime "org.netbeans.html:net.java.html.boot.fx:1.7.2"
    testAnnotationProcessor "org.netbeans.html:net.java.html.boot:1.7.2"
}
